Deciding whether to implement a traditional machine learning (ML) model or a deep learning model depends on various factors, and it's important to consider the following aspects when making your choice:

Data Volume: Deep learning models typically require a large amount of data to perform well. If you have a small dataset, traditional ML models might be more appropriate because they can generalize better from limited data.

Data Complexity: Deep learning models excel at handling complex data with many features or high-dimensional data, such as images, audio, and text. If your data has inherent hierarchical structures or complex patterns, deep learning might be suitable.

Task Type: Consider the type of machine learning task you're dealing with. For simpler tasks like linear regression, classification, or clustering, traditional ML models are often sufficient. Deep learning models shine in tasks that involve natural language processing (NLP), computer vision, speech recognition, and other complex tasks.

Interpretability: Traditional ML models are generally more interpretable. If understanding the decision process of the model is critical (e.g., in healthcare or finance), you may prefer traditional ML models.

Training Time: Deep learning models tend to have longer training times, especially with large datasets and complex architectures. Traditional ML models typically train faster.

Computational Resources: Deep learning models demand significant computational resources, including GPUs or TPUs. Make sure you have access to the required hardware.

Model Complexity: Deep learning models can have a vast number of parameters and complex architectures. If a simpler model can provide a satisfactory solution, opt for traditional ML to reduce model complexity.

# **ANN->Fully connected layer ->Feed forward network**
## ANN for classification

# **(1) Importing the libraries**

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf #Importing tensorflow for deep learning
#Here at tf-2.0, Keras is integrated with it by default

In [6]:
tf.__version__ #For checking the version of tensorflow

'2.14.0'

# **(2) Data Preprocessing**

## Importing Dataset and

In [7]:
dataset=pd.read_csv("Churn_Modelling.csv")
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

In [8]:
print(X[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


## No Missing Values, so going for Categorial Datas Encoding
###(1)Encoding the Gender, where order matters as male should a number and female represents a number, from simple labeling

In [9]:
# Here order matters for gender, encode the female or male nothing much comlicated, only 0 and 1
from sklearn.preprocessing import LabelEncoder #For that using labelEncoder mainly for binaryType Encoding (Yes or No)
le=LabelEncoder()
X[:,2]=np.array(le.fit_transform(X[:,2]))# Dependent variable vector doesnot have to have numpy Array
print(X[0])

[619 'France' 0 42 2 0.0 1 1 1 101348.88]


###(2)Encoding the CountryName, where order doesnot matters, so going for HotEcoding (3-countries)

In [10]:
#(1)Encoding the CountryName, where order doesnot matters, so going for HotEcoding (3-countries)
from sklearn.compose import ColumnTransformer # Used for tansforming into encodes
from sklearn.preprocessing import OneHotEncoder # Encoding type, That is HOtEncoding
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
#For transformer: 1-Arg= Which kind of transformation that is Encoding
                 # 2-Arg= Which Encoding that HotEncoding
                 # 3-Arg which indexs want we to encode: col-index number
#For remainder=passthourgh: If not applied, then hot encoding done from 0 to secondlast col by default

#Now lets connect the above object with the input-Matrix X:
#Unlike for missing value diferent steps for fitting and tranforming, here module has both in one
X=np.array(ct.fit_transform(X)) #ct.fit_trans donot returns the matrix into numpy array but X dataset should be numpyArray
print(X[0])#The resultant replacement by the dummyVaraibles, they move to first column

[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


## Splitting dataset

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0,test_size=0.3)

##Feature Scaling as here we are doing classification

In [12]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
X_train=sc_x.fit_transform(X_train)
X_test=sc_x.transform(X_test)

# **(3) Building ANN**

## Initializing the ANN
### Here will be creating Variable which noting but a ANN-variable as an object of certain sequatiall-class, which allow to build ANN as sequence of layer

In [13]:
ann=tf.keras.models.Sequential() #Class from models module from Keras library integrated with tf
#Initilases the ann-variable as sequence of layers, ann object of Sequntial Class

## Adding the input layer and first hidden layer

In [14]:
#Right now we have to add fully connected Layer(ANN) will be build as an object of DenseClass
#From the instance of the Sequantial-Class, ann object has add method for adding new DenseClass-object
ann.add(tf.keras.layers.Dense(units=6,activation='relu')) #DenseClass will create fully connect layer of the object and automatically add the input layer in object
#The argument(1) "units" inside the Dense represents the number of Neurons in the layer, can get by experimenting with all numbers for optimum value
#Argumnet(2), for fully conected layer, relu is best activation function
#All the features would be the input-Neuron of the input-layer
# Add method can add any layer, specification comes inside the argumnet that is hyperparameter(parameter)


## Adding the second layer

In [15]:
#Same adding the new layer required same code and we are putting the number of neurons same
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## Adding the output layer

In [16]:
#Hence this will also add output layer
#Hence we have Y as 0 or 1, then in that we require only one neuron, we have more classes like if classes are 3 we required 3 neurons, in which they have hotEncoded(if in string) and represented in 3neuron
#And here at the activation function would required is sigmoid function as we have binary classes and it would also provide the prob
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid')) #for nonBinary, activation would be softmax

# **(4) Training the ANN**

## Compiling the ANN with optimizerr,loss function and a metric

In [17]:
#From optimizer the model would update the weights to reduce the error-cost, so here we would use the GradientDescnt, that is stochastics Gradient Descent which would update weights after each iterations -> 'adam'
#For loss-function we would consider the binary_crossentropy -> for binary-classification and for non-binary-classification -> categorical_classentropy
#Here the metrice takes the list which gonna evaluate the ANN, but here we choose the main one

ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

##Training the model

In [18]:
ann.fit(X_train,Y_train,batch_size=32,epochs=100)
#Rather than compare the loss and alter weights, would do after certain batch, efficient-32, compsarison takes place as batch_learning is more efficient for training artificaial neural network
# 1-epoch refers counter goes from whole training dataset once, but once is not eough for neural ent for finding the correlation of features with the dependet var


Epoch 1/100
219/219 [==============================] - 2s 3ms/step - loss: 0.6114 - accuracy: 0.6857
Epoch 2/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4869 - accuracy: 0.7976
Epoch 3/100
219/219 [==============================] - 1s 3ms/step - loss: 0.4645 - accuracy: 0.7977
Epoch 4/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4517 - accuracy: 0.7977
Epoch 5/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4399 - accuracy: 0.8017
Epoch 6/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4270 - accuracy: 0.8087
Epoch 7/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4125 - accuracy: 0.8243
Epoch 8/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4005 - accuracy: 0.8294
Epoch 9/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3909 - accuracy: 0.8350
Epoch 10/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3836 - accura

# **(4) Prediction and Evaluating the model**

In [19]:
# Predicting the a test value
# Encode the strings
# We have to also scale the input as the model is train on the same scaled data and expects the input further in same scalling
print(ann.predict(sc_x.transform([[1.0,0.0,0.0,600,1,40,3,60000,2,1 ,1,50000]])))
#Hnce the sigmod activation function is at output layer so it would give the probability of leaving

1/1 [==============================] - 0s 95ms/step
[[0.03887982]]


In [20]:
# If you want only "yes" or "no", not wanted the probability simply add ">0.5", 0.5 here will act like threeshold value in the sigmoid, in which value greater than 0.5 will be True -> customer will exit, else no
# You could change the threshold 0.5 to any of number here, as per requirement
print(ann.predict(sc_x.transform([[1.0,0.0,0.0,600,1,40,3,60000,2,1 ,1,50000]]))>0.5)

1/1 [==============================] - 0s 25ms/step
[[False]]


In [38]:
#Example for greaqter than 0.5 -> True, exit
print(ann.predict(sc_x.transform([[0.0,0.0,1.0,900,1,44,3,10000,5,1 ,1,500000]])))
print(ann.predict(sc_x.transform([[0.0,0.0,1.0,900,1,44,3,10000,5,1 ,1,500000]]))>0.5)

1/1 [==============================] - 0s 26ms/step
[[0.9998617]]
1/1 [==============================] - 0s 22ms/step
[[ True]]


In [43]:
#Calculating Y_pred
Y_pred=(ann.predict(X_test)>0.5)

94/94 [==============================] - 0s 2ms/step


In [41]:
np.column_stack((Y_test,Y_pred))

array([[0, 0],
       [1, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [1, 1]])

## Confusion Matrix

In [44]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test,Y_pred))

[[2267  112]
 [ 310  311]]


In [45]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred))

0.8593333333333333
